"""position column
Jello/migrations/versions/57e8824463c1_position_column.py
Revision ID: 57e8824463c1
Revises: 27467c431be5
Create Date: 2023-07-03 12:08:34.316994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8824463c1'
down_revision = '27467c431be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('card_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('card_labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('card_labels', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('card_comments', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    # ### end Alembic commands ###
